### PR TITLE
display the correct preview url when using the preview option

### PR DESCRIPTION
**Pull request by joannaskao**

### CODE REVIEW

**Comment by joannaskao** [comment]
@aendrew Should we maybe make the new staging bucket idea that into a new issue/PR? This PR is (hopefully) to correct the displayed URL for projects deployed to preview — it shouldn't change where anything is currently deployed.

**Comment by aendrew** [comment]
@joannaskao Agreed, merging.

**Comment by callumlocke** [comment]
The tests didn't pass?

**Comment by aendrew** [comment]
@callumlocke Whups, sorry — not sure how I didn't notice that...

**Pull request merged**
